### ISSUE TITLE
Digit Destroyer

### ISSUE THREAD

**Issue by shaneo88** [Sidetalker/TapMonkeys#10]
Finger Monkey level 21 costs $16.37
Goofkey level 21 costs $37.64
Digit Destroyer level 30 costs $6.74

**Comment by Sidetalker** [comment]
The balance really needs to be thought through... In this case I wanted to make sure really low cost multipliers (1.01) worked. You can find monkey information here: http://sideapps.com/tapMonkeys/monkeys.html . Leaving this open as a reminder to sit down and think about balance.

**Comment by Sidetalker** [comment]
Balance is at least sorta fixed
