### ISSUE TITLE
Negative letters. 

### ISSUE THREAD

**Issue by shaneo88** [Sidetalker/TapMonkeys#4]
Every time I want to level up Word, I save up 10 letters and buy the next level. It takes me back to -6 letters. 

Not sure if this is intended, but surely you can't have less than 0.

**Comment by Sidetalker** [comment]
I'll get to the bottom of it - there's a good chance it's affecting the other purchases too.

**Comment by Sidetalker** [comment]
Fixed in 0.0.4.3
